name: .NET

on:
  push:
    branches: [ "main_m" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Configure Git
      run: |
        git config --local user.name "siphonhata"
        git config --local user.email "siphonhata@gmail.com"
        
    - name: Create Pull Request
      run: |
        git checkout master
        git merge main_m
        git push origin master
        
    - name: Merge Pull Request
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create --base master --head main_m --title "Auto PR from main_m to master" --body "Automated pull request to merge changes from main_m to master."
        gh pr merge --auto
